language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

sudo: false

install:
    - composer self-update
    - composer install --prefer-source

script:
    - ./vendor/bin/phpcs --standard=PSR2 src/ tests/
    - ./vendor/bin/phpunit
